version: '3.1'
services:
  mainApp:
    build: ./mainApp
    container_name: mainApp
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - stats.server.url=http://localhost:9090
      - spring.datasource.url=jdbc:postgresql://localhost:5432/ewm


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "7777:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit

  statsApp:
    build: ./statsApp
    container_name: statsApp
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - spring.datasource.url=jdbc:postgresql://localhost:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "8888:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
