version: '3.1'
services:
  mainapp:
    build: ./mainapp
    container_name: mainapp
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "7777:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "ewm"
      POSTGRES_USER: "shareit"
      POSTGRES_PASSWORD: "shareit"

  statsapp:
    build: ./statsapp
    container_name: statsapp
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "8888:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "stats"
      POSTGRES_USER: "shareit"
      POSTGRES_PASSWORD: "shareit"
