DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS events CASCADE;

DROP TABLE IF EXISTS compilations CASCADE;

DROP TABLE IF EXISTS requests CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS compilation_events CASCADE;

DROP TABLE IF EXISTS reviews CASCADE;



CREATE TABLE IF NOT EXISTS users
(
    user_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             varchar(50) NOT NULL,
    email            varchar(50) NOT NULL UNIQUE,
    initiator_rating double precision,
    reviewer_rating  double precision
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         text                                                       NOT NULL,
    category_id        BIGINT REFERENCES categories (category_id)                 NOT NULL,
    description        text                                                       NOT NULL,
    event_date         TIMESTAMP                                                  NOT NULL,
    initiator_id       BIGINT REFERENCES users (user_id)                          NOT NULL,
    paid               boolean                                                    NOT NULL,
    participant_limit  BIGINT,
    created_on         TIMESTAMP,
    published_on       TIMESTAMP,
    request_moderation boolean,
    confirmed_requests BIGINT,
    state              text CHECK (state IN ('PUBLISHED', 'PENDING', 'CANCELED')) NOT NULL,
    title              text                                                       NOT NULL,
    available          boolean,
    lat                float,
    lon                float,
    views              BIGINT,
    rating             double precision,
    rating_flag        boolean
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       text CHECK (status IN ('CONFIRMED', 'PENDING', 'CANCELED', 'REJECTED')) NOT NULL,
    event_id     BIGINT REFERENCES events (event_id)                                     NOT NULL,
    requester_id BIGINT REFERENCES users (user_id)                                       NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned         boolean,
    title          text NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    CE_compilation_id BIGINT REFERENCES compilations (compilation_id),
    CE_event_id       BIGINT REFERENCES events (event_id)
);

CREATE TABLE IF NOT EXISTS reviews
(
    review_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    BIGINT REFERENCES events (event_id) NOT NULL,
    reviewer_id BIGINT REFERENCES users (user_id)   NOT NULL,
    review      BOOLEAN                             NOT NULL,
    comment     TEXT,
    created     timestamp without time zone         NOT NULL
);
