DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS events CASCADE;

DROP TABLE IF EXISTS compilations CASCADE;

DROP TABLE IF EXISTS requests CASCADE;

DROP TABLE IF EXISTS locations CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS compilation_events CASCADE;



CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(50) NOT NULL,
    email   varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         text                                                       NOT NULL,
    category_id        BIGINT REFERENCES categories (category_id)                 NOT NULL,
    description        text                                                       NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE                                NOT NULL,
    initiator_id       BIGINT REFERENCES users (user_id)                          NOT NULL,
    paid               boolean                                                    NOT NULL,
    participant_limit  BIGINT,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation boolean,
    confirmed_requests BIGINT,
    state              text CHECK (state IN ('PUBLISHED', 'PENDING', 'CANCELED')) NOT NULL,
    title              text                                                       NOT NULL,
    available          boolean,
    lat                float,
    lon                float,
    views              BIGINT
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       text CHECK (status IN ('CONFIRMED', 'PENDING', 'CANCELED')) NOT NULL,
    event_id     BIGINT REFERENCES events (event_id)                         NOT NULL,
    requester_id BIGINT REFERENCES users (user_id)                           NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS locations
(
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    BIGINT REFERENCES events (event_id) NOT NULL,
    lat         NUMERIC                             NOT NULL,
    lon         NUMERIC                             NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned         boolean NOT NULL,
    title text NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    event_id       BIGINT REFERENCES events (event_id),
    compilation_id BIGINT REFERENCES compilations (compilation_id)
);
